import { User } from "../models";

export const SampleUser: User = new User({
  email: "username@email.com",
  _emailConfirmed: true,
  terms: true,
  _joined: new Date("March 22, 1856"),
  _token: "abcedfghijklmnop",
  username: "DemoUser",
  state: "TX",
  authority: 0,
});

export const SampleData = [
  {
    "clients": {
      "entityPId": 83,
      "number": "1",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 83,
      "companyName": "New Test Company 2",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 92,
      "number": "0",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 92,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 99,
      "number": "2",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 99,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 101,
      "number": "3",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 101,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 103,
      "number": "4",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 103,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 104,
      "number": "5",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 104,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 106,
      "number": "6",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 106,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 108,
      "number": "7",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 108,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 114,
      "number": "8",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 114,
      "companyName": "",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 127,
      "number": "9",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 127,
      "companyName": "Radioactive Isolation Consortium",
      "dbaName": "RIC",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8731",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 130,
      "number": "90010",
      "name": "DKHING ASSETS",
      "deleted": false,
    },
    "companies": {
      "entityPId": 130,
      "companyName": "Full Circle",
      "dbaName": "Dr Smoothie Enterprises",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "2087",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 134,
      "number": "11",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 134,
      "companyName": "Pimg",
      "dbaName": "PYM LLC",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5012",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 153,
      "number": "12",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 153,
      "companyName": "Structured Capital Corp",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8742",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 156,
      "number": "13",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 156,
      "companyName": "Debsan The Decorating Store",
      "dbaName": "Debsan Wallpaper & Pnt Co Inc",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5231",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 163,
      "number": "14",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 163,
      "companyName": "B & F Sales & Service Ltd",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5599",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 168,
      "number": "15",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 168,
      "companyName": "Ringleader, Inc.",
      "dbaName": "Ringleader, Inc.",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "7372",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 198,
      "number": "16",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 198,
      "companyName": "Kiss Equipment Corp",
      "dbaName": "Powder Coating System Div",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "3567",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 201,
      "number": "17",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 201,
      "companyName": "Advanced Engineering Tech",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8731",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 204,
      "number": "18",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 204,
      "companyName": "Martys Meals  Inc.",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "2047",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 206,
      "number": "19",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 206,
      "companyName": "Balanced Body Functional Medicine",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8011",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 211,
      "number": "20",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 211,
      "companyName": "Cross Roads general stores .com",
      "dbaName": "Murrays Lures",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "7331",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 246,
      "number": "21",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 246,
      "companyName": "Protocol Agency Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "7361",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 250,
      "number": "22",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 250,
      "companyName": "Capital Optical",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5995",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 254,
      "number": "23",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 254,
      "companyName": "Artesia Glass Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "1793",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 256,
      "number": "24",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 256,
      "companyName": "Cadd Connection Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8711",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 258,
      "number": "25",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 258,
      "companyName": "1276473 Ontario Limited",
      "dbaName": "Ambrosia Natural Foods",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5499",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 260,
      "number": "26",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 260,
      "companyName": "Milliken Mechanical  Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "1711",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 262,
      "number": "27",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 262,
      "companyName": "Right Media Solutions Inc.",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8741",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 264,
      "number": "28",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 264,
      "companyName": "Smith Brothers, Inc.",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 266,
      "number": "29",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 266,
      "companyName": "Z Abrasives  LLC",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "50850801",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 268,
      "number": "30",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 268,
      "companyName": "Global Promotions  Inc.",
      "dbaName": "FIN GPS",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "87439902",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 272,
      "number": "31",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 272,
      "companyName": "Weston Kia",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5511",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 274,
      "number": "32",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 274,
      "companyName": "Cadd Connection Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8711",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 276,
      "number": "33",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 276,
      "companyName": "Astound Group Inc.",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 278,
      "number": "34",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 278,
      "companyName": "1276473 Ontario Limited",
      "dbaName": "Ambrosia Natural Foods",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5499",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 280,
      "number": "35",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 280,
      "companyName": "Debsan The Decorating Store",
      "dbaName": "Debsan Wallpaper & Pnt Co Inc",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5231",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 282,
      "number": "36",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 282,
      "companyName": "Cassco Machines",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "3542",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 286,
      "number": "37",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 286,
      "companyName": "Cadd Connection Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8711",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 288,
      "number": "38",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 288,
      "companyName": "Cadd Connection Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "8711",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 290,
      "number": "39",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 290,
      "companyName": "Comprehensive Technical Group",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5999",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 292,
      "number": "40",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 292,
      "companyName": "Comprehensive Technical Group",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5999",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 294,
      "number": "41",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 294,
      "companyName": "Comprehensive Technical Group",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5999",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 296,
      "number": "42",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 296,
      "companyName": "Comprehensive Technical Group",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5999",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 298,
      "number": "43",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 298,
      "companyName": "Imaging Supplies Company Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5112",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 326,
      "number": "44",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 326,
      "companyName": "Airborne Support, Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "4959",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 328,
      "number": "45",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 328,
      "companyName": "Intercept Technology Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "5734",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 332,
      "number": "46",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 332,
      "companyName": "Protocol Agency Inc",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "7361",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 346,
      "number": "47",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 346,
      "companyName": "Smith Brothers, Inc.",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3980,
      "number": "48",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3980,
      "companyName": "In Harmony Sustainable Landscapes",
      "dbaName": "test dba",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "0782",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3983,
      "number": "49",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3983,
      "companyName": "Fake Company Name",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3985,
      "number": "50",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3985,
      "companyName": "DECKTEC",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "1521",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3987,
      "number": "51",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3987,
      "companyName": "Fake Company Inc.",
      "dbaName": "FC Inc",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "2344",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3989,
      "number": "52",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3989,
      "companyName": "Test Values LLC",
      "dbaName": "TV LLC",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "1234",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 3991,
      "number": "53",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 3991,
      "companyName": "Not A Real Company",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4001,
      "number": "54",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4001,
      "companyName": "Protempo Group",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "7389",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4003,
      "number": "55",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4003,
      "companyName": "Quality Life Homes",
      "dbaName": "",
      "numberOfEmployees": null,
      "lineOfBusiness": "",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": "",
      "yearStarted": null,
      "sicCode": "1521",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4006,
      "number": "63221",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4006,
      "companyName": "Sunrise Floor Systems LLC",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Floor Maintenance; They maintain and clean a huge number of grocery store c",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PyjAMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4007,
      "number": "63225",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4007,
      "companyName": "Suzuki of Western Mass., Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "John Deere Dealer also sells Suzuki motorcycles and Power boats (<5% of tot",
      "sales": 4570000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxrrMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4008,
      "number": "63217",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4008,
      "companyName": "Commercial Health Centre and Related Companies",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "5-Location Opioid Addiction outpatient treatment centers. Each center opera",
      "sales": 1710000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003Pym4MAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4009,
      "number": "63224",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4009,
      "companyName": "Classic Tile & Mosaic",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Sources & sells unique, high quality stone, marble & tile.",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000006SxLiMAK",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4010,
      "number": "63223",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4010,
      "companyName": "Rocky Mountain Shooters Supply",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Buy, sell & trade firearms direct to consumer new & used. RMSS also provide",
      "sales": 5100000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxgtMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4011,
      "number": "63219",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4011,
      "companyName": "Braxton-Grant Technologies Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Computer Related Services Master cyber security tools integrators in both g",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PyGNMA0",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4012,
      "number": "63220",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4012,
      "companyName": "Building Performance Specialist",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Drywall/insulating contractorService Offer: Residential and commercial",
      "sales": 1769161,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000006SxLTMA0",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4013,
      "number": "63222",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4013,
      "companyName": "Impact Sign & Graphics LLC/Impact Sign & Graphics of Nevada LLC",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Company was founded in 2011. They focus on banners, interior signs, dimensi",
      "sales": 6755186,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxbUMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4014,
      "number": "63226",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4014,
      "companyName": "10-8 Emergency Vehicle Service",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Fire Department Equipment & Supls-Mfrs",
      "sales": 3532549,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PyzhMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4015,
      "number": "60905",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4015,
      "companyName": "Euro-Can Marble & Granite Ltd",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Marble & Granite Fabricators & InstallersCommercial, Multi-family, High-e",
      "sales": 3000000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PlgrMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4016,
      "number": "60906",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4016,
      "companyName": "Alliance Mercantile Inc. & Related Companies",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Mfg & Dist of Consumer products, Including safety books, Safety apparel, Gl",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4017,
      "number": "60907",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4017,
      "companyName": "Datrend Systems Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Mfg of Bio Med Testing equipment, used to test, calibrate & monitor other B",
      "sales": 3160000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "3829",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4018,
      "number": "60981",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4018,
      "companyName": "Blue Line Moving & Storage",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Full service moving & storage/Residential & Commercial",
      "sales": 0,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4019,
      "number": "60982",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4019,
      "companyName": "Terminal Gravity Brewing Co Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Microbrewery with Restaurant",
      "sales": 2209049,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4020,
      "number": "60983",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4020,
      "companyName": "Curtis Liquor Stores Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Retail Liquor/2 locations started in 76",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "5921",
      "naics": "a0SA0000003PxsQMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4021,
      "number": "60984",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4021,
      "companyName": "Power Arizona LLC.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Non-emergency medical transportation service",
      "sales": 0,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "4119",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4022,
      "number": "60985",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4022,
      "companyName": "Museo/Steve Maturo & Associates Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Museo is a high end furniture store that specialized in Europen lines mainl",
      "sales": 1400000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxqoMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4023,
      "number": "60992",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4023,
      "companyName": "Bex Logistics Inc. & Bex FF Services Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": 'Trucking & Logistics/Major trucking clients are Fedex "Smart Post" & Roadru',
      "sales": 6540000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxvAMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4024,
      "number": "61028",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4024,
      "companyName": "Home Controls Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Wholesaler & distributor of home automation products",
      "sales": 7236309,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4025,
      "number": "61082",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4025,
      "companyName": "K&F Coffee Roasters",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Private label coffee roasters & distributors. Est'd in 83",
      "sales": 3100000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "2095",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4026,
      "number": "61083",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4026,
      "companyName": "Indio Spirits Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Operates as a distillery & tasting room. Primary mkt is premium whiskies, s",
      "sales": 1700000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4027,
      "number": "61084",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4027,
      "companyName": "Country Save Products Corp.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Environmentally safe laundry detergent mfg",
      "sales": 1748750,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4028,
      "number": "61085",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4028,
      "companyName": "Red River Tool & Die LLC.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Full Service Tool & Die/Automotive/Steel/Aerospace/Mining",
      "sales": 0,
      "websiteUrl": "https://www.redrivertd.com/",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "3544",
      "naics": "a0SA0000003Pm6XMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4029,
      "number": "61094",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4029,
      "companyName": "Putnam Mechanical LLC.",
      "dbaName": "",
      "numberOfEmployees": 16,
      "lineOfBusiness": "Residential & Commercial Heating Vent, AC & Plumbing",
      "sales": 2700000,
      "websiteUrl": "www.putnammechanical.com",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 2006,
      "sicCode": "1711",
      "naics": "a0SA0000006SxLJMA0",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4030,
      "number": "61156",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4030,
      "companyName": "5 Star Burgers",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Fast Food Restaurant 4 location",
      "sales": 5410660,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4031,
      "number": "61157",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4031,
      "companyName": "Earth Construction Corp.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "General Contractors doing rehab work for State & City Municipalities, MTA,",
      "sales": 2300000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4032,
      "number": "61172",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4032,
      "companyName": "Endoco LLC.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Distributor of consumable dental supplies",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4033,
      "number": "63323",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4033,
      "companyName": "Carter Associates, Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Engineering & Land Surveying, Company was founded in 1911. This company has",
      "sales": 2337589,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PyLcMAK",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4034,
      "number": "63321",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4034,
      "companyName": "D.A.D. Sales & Service, Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Trailers-Automobile Utility Sports Etc.",
      "sales": 1404785,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4035,
      "number": "63317",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4035,
      "companyName": "Green Prosthetic's and Orthotics, Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Leading producer of prosthetics and orthotics in the NE region of the Unite",
      "sales": 2526054,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PxaWMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4036,
      "number": "63322",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4036,
      "companyName": "Square One B.V.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Computer Software, Vector graphics (converting pixelated images into smooth",
      "sales": 274548,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4037,
      "number": "63326",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4037,
      "companyName": "Blazer Building Texas",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Commercial Construction company that specializes in apartment complexes, la",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4038,
      "number": "63324",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4038,
      "companyName": "Morningstar Care Homes",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Assisted living facility with multiple locations & approx. 93 beds serving",
      "sales": 4200000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003Pyx7MAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4039,
      "number": "63327",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4039,
      "companyName": "Shucks Maine Lobster",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "2092 Main Lobster Products",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4040,
      "number": "63330",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4040,
      "companyName": "Dewberry Farm",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Agri-Entertainment. 150 acre amusement park, corn maze, Christmas Tree farm",
      "sales": 2447657,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PyyAMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4041,
      "number": "61229",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4041,
      "companyName": "Cody Builders Supply Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "structural and miscellaneous metals fabricator/team of veteran steel fabric",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4042,
      "number": "63328",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4042,
      "companyName": "Training Systems Design, Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Corporate training (Mostly Fortune 100-500) in areas such as cognitive psyc",
      "sales": 2700000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PykmMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4043,
      "number": "61247",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4043,
      "companyName": "Unitech Training Academy",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "-for profit technical schools specializing in health care related courses o",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "8331",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4044,
      "number": "61228",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4044,
      "companyName": "Valley Precast Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Mfg of precast concrete products used primarily in septic tanks, sewers, ta",
      "sales": 0,
      "websiteUrl": "http://valleyprecast.com/",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "3271",
      "naics": "a0SA0000003PlgXMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4045,
      "number": "61230",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4045,
      "companyName": "Vee Gee Scientific Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Scientific Equipment/Lab Supplies",
      "sales": 1694168,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "5049",
      "naics": "a0SA0000003PxdQMAS",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4046,
      "number": "61231",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4046,
      "companyName": "TechGlobal Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "experts in the implementation of Commercial Off The Shelf software packages",
      "sales": 5700000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4047,
      "number": "61221",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4047,
      "companyName": "Ken Caryl Glass Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Glass Contractor/Commercial/Industrial/Residential No auto glass.",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4048,
      "number": "61222",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4048,
      "companyName": "Critical Path MetalWorks Inc.",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Fabricator of Steel, Stainless & Aluminium/Job Shop",
      "sales": 3440000,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "a0SA0000003PlisMAC",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
  {
    "clients": {
      "entityPId": 4049,
      "number": "61245",
      "name": null,
      "deleted": false,
    },
    "companies": {
      "entityPId": 4049,
      "companyName": "Ewing Group",
      "dbaName": "",
      "numberOfEmployees": 0,
      "lineOfBusiness": "Gen. Contractor, Commercial,  Industrial,  Walmart, Supermarkets, Design/Bu",
      "sales": null,
      "websiteUrl": "",
      "statedRevenue": null,
      "businessDescription": "",
      "comments": null,
      "yearStarted": 0,
      "sicCode": "",
      "naics": "",
      "estRevenue": null,
      "estEBIDTA": null,
      "isFranchise": null,
      "isRealEstateConsideration": null,
    },
  },
];
